version: "3.8"

services:
    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes:
            - ./grafana:/var/lib/grafana

    influxdb:
        image: influxdb
        volumes:
            - ./influxdb:/var/lib/influxdb/

    etawatch:
        image: vikru/etawatch
        depends_on:
            - influxdb
        environment:
            - ETA_URL=???
            - INFLUX_HOST=???