name: Docker Image mqtt-broker

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 2 17 * *'    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vikru/etawatch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        dockerfile: Dockerfile  
        snapshot: true
